---
title: 'Executive Summary: An Online Permit and Monitoring System to support the Nagoya
  Protocol'
author:
- Paul Oldham
- Hartmut Meyer
- Olivier Rukundo
date: "21 May 2016"
output: html_document
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

This concept paper sets out the concept and model for an online research permit and monitoring system to facilitate implementation of the access, benefit sharing, monitoring and reporting provisions of the [Nagoya Protocol on Access to Genetic Resources and the Fair and Equitable Sharing of Benefits Arising from their Utilization](https://www.cbd.int/abs/about/) to the [United Nations Convention on Biological Diversity](https://www.cbd.int).^[The research in this paper was conducted with the support of The Bahamas Environment, Science & Technology Commission (BEST) of the Government of the Bahamas under the UNEP/GEF project “Strengthening Access and Benefit Sharing (ABS) in the Bahamas" as set out in *Oldham, P (2015) Concepts for an Electronic Monitoring Tool. UNEP/GEF project “Strengthening Access and Benefit Sharing (ABS) in the Bahamas”*. The present paper was written with the additional support of The ABS Capacity Development Initiative through the Deutsche Gesellschaft für Internationale Zusammenarbeit (GIZ). The views expressed are solely those of the authors and should not be interpreted as reflecting the views of the Government of the Bahamas, the ABS Initiative or GIZ.] 

The core of this proposal is that Parties to the Protocol, and governments who intend to ratify or accede to the Protocol, may wish to adopt: 

> “A single electronic permit system that makes it easy to apply for permits and for government authorities to review and approve applications, monitor compliance and report on the access, benefit-sharing, compliance and reporting provisions of the Nagoya Protocol.”^[Oldham, P (2015) *Concepts for an Electronic Monitoring Tool*. UNEP/GEF project “Strengthening Access and Benefit Sharing (ABS) in the Bahamas”.] 

The majority of Parties to the Protocol will already possess national permit systems for  research involving biodiversity and genetic resources within their jurisdiction and, in the case of indigenous peoples and local communities, for research involving human subjects.^[In decision XII/12 F para.1 the Conference of the Parties decided "to use the terminology “indigenous peoples and local communities” in future decisions and secondary documents under the Convention, as appropriate." This paper uses this terminology in accordance with decision XII/12.] Research permit systems are normally the first point of contact between researchers seeking to carry out research on biodiversity and traditional knowledge and government authorities. Research permit systems have an important role to play in:

1. Implementation of the permit providing evidence of prior informed consent and mutually agreed terms foreseen in [Article 6.3(a)](https://www.cbd.int/abs/text/articles/default.shtml?sec=abs-06) of the Nagoya Protocol on access to genetic resources. 
2. Creating simplified measures on access for non-commercial research purposes under [Article 8a](https://www.cbd.int/abs/text/articles/default.shtml?sec=abs-08) with due regard to the need to address change of intent. 
3. Realising fair and equitable benefit-sharing arising from research under [Article 5](https://www.cbd.int/abs/text/articles/default.shtml?sec=abs-05) of the Protocol and its [Annex](https://www.cbd.int/abs/text/articles/default.shtml?sec=abs-37). Benefits arising from research of all types involving genetic resources may include, inter alia: funding, international collaborations, training, scientific publications, reports, patents, material transfer agreements and licenses, market approvals, clinical trials and commercial products.
4. Enhancing transparency on the utilization of genetic resources and monitoring to support compliance under [Article 17](https://www.cbd.int/abs/text/articles/default.shtml?sec=abs-17) and providing a platform for evidence based valuation of genetic resources and associated traditional knowledge. 
5. National Reporting under [Article 29](https://www.cbd.int/abs/text/articles/default.shtml?sec=abs-29) and [Decision NP-1/3](https://www.cbd.int/decisions/?id=13403) of COP-MOP1 and support for the effective operation of the [ABS Clearing House Mechanism](https://www.cbd.int/abs/theabsch.shtml).

National research permit systems have typically developed organically over time in response to specific needs for the regulation of research (e.g. in protected areas or involving threatened species). Within a country multiple authorities may hold responsibility for issuing permits (e.g. scientific bodies, environment, national parks, agriculture, marine etc.) and coordination between authorities and consistency in permit provisions may be limited. The administration of research permits will also vary from purely papers systems to electronic systems or mixtures of the two. 

This paper addresses the question of how research permit systems might be adapted to facilitate effective implementation of the Nagoya Protocol. We propose that an online electronic permit and monitoring system will: 

1.	Make it easier for Parties to the Protocol to review and administer permit applications;
2.	Make it easier for applicants to apply for and receive a permit and obtain legal certainty based on compliance with the terms and conditions of the Party providing access;
3.	Enhance the capacity of Parties to determine if a permit application triggers domestic access and benefit sharing requirements and obligations under the Nagoya Protocol;
4. Enhance the capacity of Parties to monitor compliance with permits and associated mutually agreed terms and contribute to building confidence in ABS and the Nagoya Protocol;
5.	Enhance the capacity of Parties to realise non-monetary and monetary benefits arising from both non-commercial research and commercial research and development involving genetic resources and associated traditional knowledge over the long term;
6.	 Enhance the capacity of Parties to determine the actual and potential value of genetic resources;
7.	Make it easier for Parties to meet national and international reporting requirements under the Nagoya Protocol and related international environmental agreements.

The core of this proposal is the use of “cost-effective communication tools and systems” as envisaged in Article 17.2 of the Protocol to simultaneously streamline the administration of research permits under Article 6, and make it easy for non-commercial and commercial researchers to apply for permits and report on the outcomes of research. 

Advances in information technology mean that it is now readily possible to combine electronic data from different sources. We propose that by exploiting these developments it will become possible to link permit systems with the monitoring of scientific publications, patent applications and product registrations to create an effective long term system for monitoring compliance. In the process Parties to the Protocol will be able to create an evidence base for the long term valuation of genetic resources and associated traditional knowledge. 

The concept paper is divided into 5 sections. 

- Section 1: presents the Background to the proposal; 
- Section 2: presents a Model for the online permit and monitoring system;
- Section 3: presents a set of Core Principles informing the design, maintenance and sustainability of the system;
- Section 4: Discusses the use of unique identifiers within the online system;
- Section 5: Presents a draft workplan to assist Parties interested in implementing the system; 
- The Annex: Presents the draft work plan as a set of headings for log frame development;
- Schematics: A set of process schematics demonstrating the functioning of the system.

We would emphasise that the aim of this proposal is not to impose a single model. Rather, our purpose is to present a practical model that is robust and flexible enough to respond to the different circumstances and needs of Parties to the Protocol. For this reason we present the model as a series of integrated components (or modules) that can be developed and adapted by Parties interested in implementing the model. We hope that this model will contribute to building shared capacity and collaboration between Parties interested in developing effective ways to meet the access, benefit-sharing, monitoring and reporting requirements of the Protocol. The model may also lead to contributions from research organisations, such as public collections, interested in research permits and effective monitoring of compliance.

This concept paper is intended to evolve over time and is publicly available in an open access [GitHub repository](https://github.com/poldham/abs_permits) in a variety of formats. Subject to interest in development and implementation of the model additional materials will be added over time and contributions are welcomed.  
