---
title: "Draft Workplan for Implementation of the Online Permit and Monitoring System"
author: "Paul Oldham"
date: "17 May 2016"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
IN USING THE WORDS ELEMENTS AND TASKS. IT MAY MAKE SENSE TO USE 

A,B,C for those not presently in the system and then group as Component, element and task for those that are in the system. That would follow the logic of the earlier part of the document. 
###Introduction:

This section provides a draft workplan for countries interested in implementing the model for the online permit and monitoring system outlined in the previous sections. The draft outline is divided into elements and tasks and is intended to be turned into a log frame with costed tasks as the basis for pursuing resources. We emphasise that this is a draft workplan and should be adapted in accordance with an assessment of the specific needs and existing capacities within countries. 

###4. Activities:

Activities are divided into Elements. Note that the main elements are the development of the Applicants and Authorities Portals as part of the core system. These are listed as separate elements for planning purposes but are integral parts of the online system. 

PREPARATORY

Element 1: Mapping Existing Research Permit Systems

It is essential to gain an understanding of the permit process in a country as a basis for understanding the responsibilities of different permit granting authorities and for consultations on potential ways forward in either improving existing systems or establishing new systems. 

1.	Task 1. Map permit granting authorities in a participating country and the locations of permit files in either hard copy or physical form.

2.	Task 2. Identify the persons responsible for administering permits in the country as a basis for consultations. 

3.	Task 3. Consult with permit authorities on experience to date including what has worked for them and problem areas. 

4.	Task 4. Generate process diagrams for permits within a country. 

5.	Task 5. Workshop to discuss experience and the desirability (or otherwise) of a single electronic system serving multiple permit granting authorities. 

*Expected Outcome:* Agreement on ways forward in adapting the permit system to serve the needs of permit granting authorities and applicants in response to the entry into force of the Nagoya Protocol. 

Element 2: Mapping existing permit data with the scientific and patent literature.

The prerequisite for this Element is access to permit data in either physical or (preferably) electronic form. 

Task 1. Obtain copies of permit data (preferably in electronic form) including use of confidentiality agreements. 

Task 2. Obtain scientific literature for a specific country

Task 3. Develop search patterns for patent literature using patent databases and identify appropriate tools and match criteria to distinguish between positive and negative results. 

Task 4. Identify, and, as appropriate, develop programmatic tools to facilitate automated literature and patent searches in future that minimise requirements for human intervention. 
Examples include the programmatic use of crossref or the EPO Open Patent Services or WIPO Patentscope databases and the rOpenSci and biosciences packages in languages such as R or Python. 

*Expected Outcome:* A clear baselines and overview of existing publication and patent activity that can be linked to existing research permits. This will typically involve permits issued prior to the entry into force of the Nagoya Protocol and is intended to create an evidence based understanding and electronic repository of historic data on publications and patent data.  Historic data will also serve as a means of identifying key researchers working in a country as a basis for engagement activities to discuss ways of improving the permit and reporting system following the entry into force of the Nagoya Protocol. Note that this outcome fundamentally depends on the availability of permit data for use in searches.  

Element 3: Demonstration Model and Field Testing

Objective: Develop a working sandbox/testbed model to test different approaches, identify key tools and for demonstration purposes using dummy data. 

Task 1. Develop one or more working models of the system including identifying solutions using different tools that may be best suited to the diversity of circumstances and existing capacities within a country. 

Task 2. Consult with staff from authorities involved in checking permit data on the ground (National Parks, Customs, police and others) and identify existing approaches and tools, what already works, problems encountered and potential solutions. 

Task 3. Identify how checks by local level authorities can be most effectively linked to the online permit and monitoring system. 

Task 4. Arrange field tests of solutions such as barcodes, QR code readers, html etc. with relevant authorities and adapt solutions focusing on meeting actual needs. 

Task 5. In consultation with relevant international collections identify appropriate options for the inclusion of permit data in sample labels and for sequence data.

Expected Outcome: A working model or set of models using different tools as a test bed and demonstration model using non sensitive dummy data. This may include experiments using simple forms (such as Google Forms or Wufoo), database approaches using MySQL and practical testing of barcodes, QR Codes and html tags in live environments. Field tests of mobile solutions for permit enforcement authorities will be an important activity in identifying practical solutions. 

Element 4: Developing an online electronic permit and monitoring system

Objective: Establish an electronic system for permit applications, administration, monitoring and reporting. 

Task 1. Identify organisations or partners in the country with the technical and programming capacity to develop an electronic permit system consisting of

A) An online front page
B) An applicants portal
C) An authorities portal
D) A core system (server, database, file store etc.)
E) Secure Backups
F) Mobile access linked to the system (phones and tablets)
G) A physical archive linked to the electronic system

Task 2. Develop a costed plan of implementation over a period of 3 years

Task 3. Develop a pilot system at an early stage (Year 1) accommodating the principles of agile development (iterative and flexible software development) where possible.

Task 4. Implement and continue the development of the system with clearly defined regular periodic review by users.

Task 5. Report on experience gained and future development plans (Year 2, Year 3)

Expected Outcome: A clear development plan for the system with partners and stakeholders identified. 

Element 5. Applicants Portal

Objective 1: Create a single online space for applicants to submit applications with supporting information/guidelines, to receive notification and monitor the progress of applications, to receive permits and to fulfil reporting requirements. 

Objective 2. The applicants portal will serve as an enduring homepage for the applicants where information (such as legal status information) along with links to publications, conference proceedings etc arising from the permit could, subject to confidentiality considerations, be made publicly available to highlight research on biodiversity and genetic resources in a country. THIS IS NOT AN OBJECTIVE

Element 5.1.1. Information

Task 1. Develop a guide for applicants

Task 2. Develop a checklist of required information for applicants

Task 3. Test utility with selected applicants (survey/practical tests)

Task 4. Provide information on appeals process (see authority side)
 
Element 5.1.2. Applications

Task 1. Create applicant home page system

Task 2. Establish secure username and password system

Task 3. Define data fields for applications in consultation with relevant permit granting authorities. Use checkboxes wherever possible (e.g. Marine, terrestrial, national park etc.)

Task 4. Test using services such as Google Forms or Wufoo etc. and refine to final version. 

Element 5.1.3 Notifications

Task 1. Establish a system for transmitting requests from the authority side to the applicant side with appropriate data fields (title, date, originator etc.).

Task 2. Define a standard list of information request types (authority side) while allowing authorities to provide specific details (headings for the request and content or body of the request).

Task 3. Establish a system for applicants to respond to requests and channel (email) the response to the originator with a notification. 

Task 4. Establish a system that: 

a) lists the stages in the application procedure
b) provides the name and contact details (email) for the person responsible for that stage of the procedure. 
c) updates the record upon completion to show the next stage in the procedure and persons responsible.
d) generates the permit and associated material (passes, labels, embed codes) and inform the applicant of availability by email. Accessed through the approvals section. 

Element 5.1.4 Approvals

Task 1. Create a system to generate a permit as a .pdf (links to authority generated master permit).

Task 2.  Create a system to generate a permit pass and QR code generation for mobile phones and tablets. 

Task 3. Create a system to generate labels for sample bags, jars and individual samples.

Task 4. Create a system for HTML embed codes (for sequence data/publications etc.).

Task 5. Establish uniform persistent identifiers (BS20151234) for use in conjunction with publications, patents, products and electronic data. 

Task 6. Investigate the use of persistent identifiers (BS20151234) and Barcodes/QR Codes/html tags to build redundancy into the system (triple redundancy principle)

Task 7. Test mobile readers with authorities for “permit passes” and adjust based on feedback received.

Element 5.1.5 Reporting

Task 1. Establish reporting section of the applicant site.

Task 2. Decide on mandatory and voluntary reporting options. [Legal component]

Task 3. Define required uses of unique identifiers (BS20151234, QR codes, barcode, html embed codes). [Legal component]

Task 4. Establish data fields for reporting, including, inter alia: 

a) uploads of publications (pre-print or published)
b) doi (document identifier links to publications for automated retrieval)
c) links to home pages and academic record sites such as ORCID, and social media sites such asresearchgate.com or academia.edu etc. 
d) accession numbers for sequence data or deposits of genetic material
e) locations where collected samples are stored
f) transfers of materials to third parties and the terms and conditions of transfer
g) patent applications and grants
h) products for which market approval is sought or approved
i) other information on activities arising from the permit

Task 5. Test system with selected applicants

Task 6. Adjust system based on user feedback. [Legal component]

Element 5.1.6 Appeals

Task 1. Identify grounds for appeal. [Legal component]

Task 2. Define roadmap and timeline for appeals process. [Legal component]

Task 3. Define form of documents for appeals. [Legal component]

Task 4. Identify person(s) responsible and provide contact details. [Legal component]

Task 5. Identify criteria for accepting or rejecting an appeal. [Legal component]

Task 6. Identify form of notification to applicant within system for unambiguous final acceptance or final rejection. [Legal component]

Expected Outcome: An easy to use applicants portal that provides legal certainty for applicants and contributes data to monitoring and reporting. 

Element 6: Authorities Portal

Objective: Establish an authorities portal for the administration of permit applications. 

Element 6.1 Enquiries [Legal component]

Task 1. Establish standard responses to enquiries as inputs into the online permit system.

Element 6.2 Review {Legal component]

Task 1. Develop Guide for Applicants

Task 2. Develop Applicants Checklist

Task 3. Develop checklist for completeness by authorities (authority side should match to applicant side)

Task 4. Include visual validation of unique identifier in checklist

Task 5. Develop standard notifications to applicants on receipt and completeness. 

Task 6. Develop individual authority checklist (or lists as appropriate to authority)

Task 7. Establish criteria for validating if non-commercial or commercial research (or both)

Task 8. Define next steps for non-commercial research (e.g. compliance with environmental legislation, local partners, deposit of samples etc.), taking note of Article 8(a) of the Nagoya Protocol.

Element 6.3 Negotiation [Legal component]

Task 1. Define next steps for commercial research
	
	a) Establish criteria for negotiations. [Legal component.]
	b) Identify standard list of participants in negotiations. [Legal component].
	c) Establish time frame for negotiations. [Legal component].
	d) Establish environmental legislation and procedure criteria. [Legal component].
	e) Establish criteria for benefit-sharing. Note legal component.
	f) Establish criteria on Intellectual Property Rights. Note legal component.
	g) Establish criteria for acceptance or rejection of commercial applications. Note legal component.
	h) Define written notifications. Note legal component.

Task 2. Establish checklist of environmental terms and conditions based on applicable laws and policies. Note legal component.

Element 6.4. Approve/Reject [Legal component]

Task 1. Define standard terms and conditions (menu of clauses) for use in generating permits. 

Task 2. Define areas where specific terms and conditions are likely to be needed (menu of clauses). 

Task 3. Define any supplementary (ABS or Impact) agreements to the permit. 

Task 4. Establish harmonised document identifier system (e.g. BS20151234) to ensure links between the permit and supplementary agreements are maintained across time and space. 

Task 5. System to generate .pdf permits, QR codes, barcodes, HTML embed codes and labels (see applicant side).

Element 6.5. Appeals [Legal component]

Task 1. Establish a clear and transparent appeals process.

Task 2. Develop guidance on the appeals process for authorities and applicants.

Task 3. Develop a timeline for appeals. 

Task 4. Generate standard notifications for appeals to be sent to applicants on the stage in the procedure. 

Task 5. Define the form of a clear final decision. 
Expected Outcome: An easy to use authorities portal with a clear and transparent procedure and decision-making process that serves the needs of multiple permit granting authorities over the long term. 

Element 7: Legal

Objective: Ensure that the online permit and monitoring system complies with and supports relevant national laws and the obligations under the Nagoya Protocol.

Task 1. Identify areas of the online permit and monitoring system requiring legal input.

Task 2. Engage in legal drafting for relevant elements of the permit and monitoring system.

Task 3. Collaborate with technical staff in incorporating legal elements into the system.  

Task 3. Identify future requirements for legal review.
Expected Outcome: The online permit and monitoring system complies with and supports relevant national laws and obligations under the Nagoya Protocol.

Element 8: Monitoring

Objective: Establish an effective electronic monitoring system for compliance with the terms of research permits, access and benefit-sharing agreements under the Nagoya Protocol. 

Task 1. Develop search queries key data fields from research permit data for searches of scientific literature, patent literature, product information and general web searches. 

Task 2. Identify programmatic open source tools to automate search and retrieval of data from relevant sources (scientific literature, patents, product information and general web searches.

Task 3. Identify relevant commercial databases and analytics software to facilitate monitoring. 

Task 4. Discuss and mutually agree on the most appropriate monitoring tools for use in the partner country. 

Task 5. Provide training for key staff focusing on local capacity

Task 6. Provide follow up training as required

Task 7. Build a network of staff engaged in monitoring from participating countries. 

Task 8. Develop an open access manual on ABS monitoring for use by staff and in training future trainers.  

Expected Outcome: An effective electronic monitoring system adapted to the requirements of the participating country that is sustainable over the long term. 

Element 9: Reporting 

Objective: Facilitate national and international reporting under the Nagoya Protocol and other relevant agreements linked to the permit system. 

Task 1. Identify national and international reporting requirements under the Nagoya Protocol and, as appropriate, related international environmental agreements. 

Task 2. Identify components of permit and related datasets that can contribute to reporting requirements. 

Task 3. Establish programmatic solutions to automate data generation to meet reporting requirements in the formats required. 

Expected Outcome: A system that provides information from the permit system in a form for inclusion in national reports and linked to the Nagoya Protocol Clearing House Mechanism.

Element 10. Data Archive

Objective: Establish a long term data archive for research permits and access and benefit-sharing agreements.

Task 1. Establish Data archive in the core system including permit data in text and table form and stored as .pdf.

Task 2. Establish secure back up infrastructure and routines

Task 3. Establish secure Cloud back up (see task 2)

Task 3. Harmonise with physical archives or, as necessary, establish physical archives. 

Expected Outcome: A long term data archive linked to a well organised physical archive.  


