---
title: 'Executive Summary: An Online Permit and Monitoring System under the Nagoya
  Protocol'
author:
- Paul Oldham
- Hartmut Meyer
- Olivier Rukundo
date: "21 May 2016"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

This paper sets out the concept and model for an online research permit and monitoring system to facilitate implementation of the access, benefit sharing, monitoring and reporting provisions of the [Nagoya Protocol on Access to Genetic Resources and the Fair and Equitable Sharing of Benefits Arising from their Utilization](https://www.cbd.int/abs/about/) to the [United Nations Convention on Biological Diversity](https://www.cbd.int).^[The research in this paper was conducted with the support of The Bahamas Environment, Science & Technology Commission (BEST) of the Government of the Bahamas under the UNEP/GEF project “Strengthening Access and Benefit Sharing (ABS) in the Bahamas" as set out in *Oldham, P (2015) Concepts for an Electronic Monitoring Tool. UNEP/GEF project “Strengthening Access and Benefit Sharing (ABS) in the Bahamas”*. The present paper was written with the additional support of the ABS Capacity Development Initiative through the Deutsche Gesellschaft für Internationale Zusammenarbeit (GIZ). The views expressed are solely those of the authors and should not be interpreted as reflecting the views of the Government of the Bahamas, the ABS Initiative or GIZ.] 

The majority of Parties to the Protocol will already possess national permit systems for non-commercial and commercial research involving biodiversity and genetic resources within their jurisdiction and, in the case of indigenous peoples and local communities, for research involving human subjects. Research permit systems are normally the first point of contact between researchers seeking to carry out research on biodiversity and traditional knowledge and government authorities. As such, research permit systems are an important enabling condition for the implementation of the access permit foreseen under [Article 6.3(a)](https://www.cbd.int/abs/text/articles/default.shtml?sec=abs-06) of the Nagoya Protocol on access to genetic resources. The research enabled by research permits **[typically involves]** research collaborations, funding, scientific publications, reports, patent applications, material transfer agreements and licenses, market approvals, clinical trials and commercial products are major components in the realisation of monetary and non-monetary benefit-sharing under [Article 5](https://www.cbd.int/abs/text/articles/default.shtml?sec=abs-05) of the Protocol and its [Annex](https://www.cbd.int/abs/text/articles/default.shtml?sec=abs-37).

Research permit systems provide the foundation for monitoring the utilization of genetic resources and associated traditional knowledge and enhancing knowledge and understanding of the value of national biodiversity. The information provided in research permits is the basis for identifying scientific publications, patents, and products arising from utilizations of genetic resources and associated traditional knowledge. This in turn allows countries to establish an evidence base on the value of biodiversity and associated traditional knowledge within their jurisdiction. That is, research permits are central to the capacity of countries to know what research and development is taking place with genetic resources and associated traditional knowledge originating from their jurisdictions. The Nagoya Protocol addresses monitoring and enhancing transparency about the utilization of genetic resources in [Article 17](https://www.cbd.int/abs/text/articles/default.shtml?sec=abs-17). This includes the use of the access permit in [Article 6.3(a)](https://www.cbd.int/abs/text/articles/default.shtml?sec=abs-06) as an Internationally Recognized Certificate of Compliance (IRCC) providing evidence of prior informed consent and mutually agreed terms that will be made available to the [ABS Clearing House Mechanism](https://www.cbd.int/abs/theabsch.shtml). 

Monitoring is also linked with national reporting on implementation of obligations under the Nagoya Protocol by Parties is addressed under [Article 29](https://www.cbd.int/abs/text/articles/default.shtml?sec=abs-29) and supported by [Decision NP-1/3](https://www.cbd.int/decisions/?id=13403) of the COP-MOP. Research permit systems form a potentially valuable element in national reporting on ABS obligations through the provision of summary information on topics such as the number of permits granted, types of research, such as non-commercial research under [Article 8(a)](https://www.cbd.int/abs/text/articles/default.shtml?sec=abs-08) or commercial research and development, as well as the longer term outcomes of access and benefit-sharing agreements linked to permits.  

Research permit systems have typically have developed organically over time to address specific needs for the regulation of research (e.g. in protected areas or involving threatened species). It appears that in many countries there will be multiple authorities with responsibility for issuing permits in accordance with their specific mandates (e.g. scientific bodies, environment, national parks, agriculture, marine etc.). Coordination between permit granting authorities may be limited and the provisions of permits granted by different authorities may not be consistent. Research permit systems will also often vary in type ranging from paper based systems to electronic systems or, as we believe will be common, will involve mixtures of manual and electronic systems and historic archives.   

This paper addresses the question of how research permit systems might be adapted to facilitate effective implementation of the Nagoya Protocol. We propose that an online electronic permit and monitoring system will: 

1.	Make it easier for Parties to the Protocol to review and administer permit applications;
2.	Make it easier for applicants to apply for and receive a permit and obtain legal certainty based on compliance with the terms and conditions of the Party providing access;
3.	Enhance the capacity of Parties to the Protocol to determine if a permit application triggers domestic access and benefit sharing requirements and obligations under the Nagoya Protocol;
4.	 Enhance the capacity of Parties to the Protocol to determine the actual and potential value of their genetic resources through a long term electronic monitoring system;
5.	Enhance the capacity of Parties to the Protocol to realise non-monetary and monetary benefits arising from both non-commercial research and commercial research and development involving genetic resources and associated traditional knowledge over the long term;
6.	Make it easier for Parties to meet national and international reporting requirements under the Nagoya Protocol and related international environmental agreements.

We propose that Parties to the Protocol, and governments who intend to ratify or accede to the Protocol, may wish to adopt: 

 “A single electronic permit system that makes it easy to apply for permits and for government authorities to review and approve applications, monitor compliance and report on the access, benefit-sharing, compliance and reporting provisions of the Nagoya Protocol.” 

The core of this proposal is the use of “cost-effective communication tools and systems” as envisaged in Article 17.2 of the Protocol to simultaneously streamline the administration of research permits under Article 6, and make it easy for non-commercial and commercial researchers to apply for permits and report on the outcomes of research. Advances in information technology mean that it is now possible to readily possible to combine data from different sources. We propose that by exploiting these developments it will become possible to link permit systems with the monitoring of scientific publications, patent applications and product registrations to create an effective long term system for monitoring compliance. In the process Parties to the Protocol will be able to create an evidence base for the long term valuation of genetic resources and associated traditional knowledge. 

The concept paper is divided into x sections. 

Section 1: presents the Background to this proposal; 
Section 2: presents a Model for the online permit and monitoring system;
Section 3: presents a set of Core Principles informing the design, maintenance and sustainability of the system;
Section 4: presents a Draft Work plan for consideration by Parties interested in implementing the system; 
The Annex: provides the Draft Work plan as a set of headings for log frame development.

We would emphasise that the aim of this proposal is not to impose a single model. Rather, our purpose is the present a practical model that is both robust and flexible enough to respond to the different circumstances and needs of Parties to the Protocol. For this reason we present the model as a series of integrated components (or modules) that can be further developed and adapted by Parties interested in implementing the model. We hope that this model will contribute to building shared capacity and collaboration between Parties interested in developing effective ways to meet the access, benefit-sharing, monitoring and reporting requirements of the Protocol and lead to contributions from public research organisations and companies in implementing effective online permit and monitoring systems.

This concept paper is intended to evolve over time and is available in html, Word, .pdf and markdown formats. The core paper is accompanied by a set of schematics and other materials that are housed in a public Git Hub repository at **[xxx]**. The evolution of the document will be marked with the use of version numbers and the revision history will be accessible through the Git Hub repository. Comments and suggestions from readers are welcomed and can be added to the electronic version of this document. Contributions to the project are governed by a widely used **[Code of Conduct](INSERT)** for online collaborations. 



